language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.2
        - python -m pip install -U pip # uses python instead of python3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install pytest-cov
  - pip3 install -r requirements.txt
script:
  - pytest --cov-report=xml --cov=automation-decoder
  - pip3 install -e .
  - python3 -m automation --help || python -m automation --help
after_success: codecov
